controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    # Use the correct parameter names for the controller
    rear_wheels_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    front_steering_joints_names: ["front_left_steer_joint", "front_right_steer_joint"]

    # Robot physical parameters from your config
    wheel_separation: 0.09   # Corresponds to wheel_track
    wheel_base: 0.1425
    wheel_radius: 0.034

    # Odometry settings
    open_loop: false
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0
