<?xml version="1.0"?>
<robot name="steer_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Include xacro for wheels. wheel.xacro includes materials.xacro and inertials.xacro -->
  <xacro:include filename="wheel.xacro"/>

  <xacro:arg name="use_ros2_control" default="true"/>
  <xacro:property name="robot_namespace" value="/steer_bot"/>

  <!-- Math constants -->
  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Robot base dimensions -->
  <xacro:property name="base_length" value="0.2" /> 
  <xacro:property name="base_width" value="0.09" /> 
  <xacro:property name="base_height" value="0.05" /> 
  <xacro:property name="base_mass" value="2.5" /> 

  <!-- Wheel link dimensions -->
  <xacro:property name="wheel_radius" value="0.034" />
  <xacro:property name="wheel_thickness" value="0.027" />
  <xacro:property name="wheel_mass" value="0.5" />

  <!-- Steering link dimensions -->
  <xacro:property name="steer_radius" value="0.05" />
  <xacro:property name="steer_thickness" value="0.02" />
  <xacro:property name="steer_mass" value="1" />

  <!-- Axle positions -->
  <xacro:property name="axle_offset" value="0.0125" />
  <xacro:property name="steer_offset" value="0.045" />

  <!-- Sensor dimensions -->
  <xacro:property name="ultrasonic_length" value="0.02" />
  <xacro:property name="ultrasonic_width" value="0.02" />
  <xacro:property name="ultrasonic_height" value="0.02" />
  <xacro:property name="ultrasonic_mass" value="0.05" />
  <xacro:property name="camera_size" value="0.03" />
  <xacro:property name="camera_mass" value="0.1" />

  <!-- SENSOR MACRO DEFINITION (No new file needed) -->
  <xacro:macro name="ultrasonic_sensor" params="prefix parent xyz rpy">
    <link name="ultrasonic_${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${ultrasonic_length} ${ultrasonic_width} ${ultrasonic_height}"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${ultrasonic_length} ${ultrasonic_width} ${ultrasonic_height}"/>
        </geometry>
      </collision>
      <xacro:solid_cuboid_inertial
          rpy="0 0 0" xyz="0 0 0"
          mass="${ultrasonic_mass}"
          x="${ultrasonic_length}" y="${ultrasonic_width}" z="${ultrasonic_height}" />
    </link>
    <joint name="ultrasonic_${prefix}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="ultrasonic_${prefix}_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>
  </xacro:macro>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="green" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:solid_cuboid_inertial 
        rpy="0 0 0" xyz="0 0 0"
        mass="${base_mass}"
        x="${base_length}" y="${base_width}" z="${base_height}" />
  </link>

  <!-- Steerable front wheels -->
  <xacro:front_wheel_lr 
    name="front_right" parent="base" reflect="-1"
    wheel_radius="${wheel_radius}" wheel_thickness="${wheel_thickness}" wheel_mass="${wheel_mass}" 
    steer_radius="${steer_radius}" steer_thickness="${steer_thickness}" steer_mass="${steer_mass}" 
    base_length="${base_length}" base_width="${base_width}" axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}" />
  <xacro:front_wheel_lr
    name="front_left" parent="base" reflect="1"
    wheel_radius="${wheel_radius}" wheel_thickness="${wheel_thickness}" wheel_mass="${wheel_mass}" 
    steer_radius="${steer_radius}" steer_thickness="${steer_thickness}" steer_mass="${steer_mass}" 
    base_length="${base_length}" base_width="${base_width}" axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}" />

  <!-- Rear wheels -->
  <xacro:rear_wheel_lr
    name="rear_right" parent="base"
    wheel_radius="${wheel_radius}" wheel_thickness="${wheel_thickness}" wheel_mass="${wheel_mass}">
    <origin xyz="${-base_length/2+axle_offset} ${-base_width/2-axle_offset} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>
  <xacro:rear_wheel_lr
    name="rear_left" parent="base"
    wheel_radius="${wheel_radius}" wheel_thickness="${wheel_thickness}" wheel_mass="${wheel_mass}">
    <origin xyz="${-base_length/2+axle_offset} ${+base_width/2+axle_offset} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>

  <!-- Camera Link -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}" />
      </geometry>
      <material name="red" /> 
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}" />
      </geometry>
    </collision>
    <xacro:solid_cuboid_inertial 
        rpy="0 0 0" xyz="0 0 0"
        mass="${camera_mass}"
        x="${camera_size}" y="${camera_size}" z="${camera_size}" />
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Ultrasonic Sensor Links -->
  <xacro:ultrasonic_sensor prefix="front" parent="base_link" xyz="${base_length/2} 0 ${base_height/2-ultrasonic_height}" rpy="0 ${90*deg_to_rad} 0" />
  <xacro:ultrasonic_sensor prefix="rear" parent="base_link" xyz="${-base_length/2} 0 ${base_height/2-ultrasonic_height}" rpy="0 ${-90*deg_to_rad} 0" />
  <xacro:ultrasonic_sensor prefix="right" parent="base_link" xyz="0 ${-base_width/2} ${base_height/2-ultrasonic_height}" rpy="0 0 ${-90*deg_to_rad}" />
  <xacro:ultrasonic_sensor prefix="left" parent="base_link" xyz="0 ${base_width/2} ${base_height/2-ultrasonic_height}" rpy="0 0 ${90*deg_to_rad}" />

  <!-- Gazebo Plugin for ros2_control -->
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find my_robot_gazebo)/config/robot_controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- ros2_control hardware interface -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="front_left_steer_joint">
      <command_interface name="position"/>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="front_right_steer_joint">
      <command_interface name="position"/>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
  </ros2_control>

</robot>
